name: Deploy nightly build documentation

on:
  push:
    branches:
      - 'main'
    paths:
      - 'genordi.py'
      - 'doc/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # - name: Check out package
      #   uses: actions/checkout@v4
      #   with:
      #     path: package

      # - name: Check out website
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
      #     path: website
      #     token: ${{secrets.PUSH_TOKEN}}
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #     SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}

      # - name: Set up git
      #   run: |
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"

      - name: Check out package
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.8'

      - name: Set up Sphinx
        run: pip install -U sphinx

      - name: Build documentation
        run: make -C doc html

      - name: Push to website
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: doc/_build/html
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: ${{ github.repository_owner }}.github.io
          user-name: ${{ github.actor_id }}
          user-email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          target-branch: main
          target-directory: docs/dev
