name: Deploy homepage

on:
  push:
    branches:
      - 'main'
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out homepage
        uses: actions/checkout@v4
        with:
          path: homepage

      - name: Check out website
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
          path: website
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Update website content
        run: rsync -av --delete --exclude docs homepage/web/ website

      - name: Deploy website
        run: |
          cd website
          git config user.name "${{ github.actor_id }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Update from ${{ github.ref }}"
          git push
